## Calculator

In [7]:
def calculator(num1,num2):
    print("addition is: ", num1+num2)
    print("subtraction is : ", num1-num2)
    print("Multiplication is: ", num1*num2)
    print("Division is: ",num1/num2)
    
calculator(2,3)

addition is:  5
subtraction is :  -1
Multiplication is:  6
Division is:  0.6666666666666666


## flag = false

In [8]:
def add_variables(x, y, z=None, flag=False):
    if flag:
        if z is None:
            return x + y
        else:
            return x + y + z
    else:
        return None

# Example 1: flag is False, so the function returns None
result = add_variables(10, 20)
print(result)  # Output: None

# Example 2: flag is True, and z is provided, so the function returns the sum of x, y, and z
result = add_variables(10, 20, 5, flag=True)
print(result)  # Output: 35

# Example 3: flag is True, and z is not provided, so the function returns the sum of x and y
result = add_variables(10, 20, flag=True)
print(result)  # Output: 30

# Example 4: flag is False, so the function returns None
result = add_variables(5, 10, flag=False)
print(result)  # Output: None


None
35
30
None


## list append

In [23]:
list1= ['savera','ansari','22','Bscs']
list1
list1.append(3.3)
list1
type(list1)
len(list1)


5

## list through for and while

In [24]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
    if "a" in x:
        newlist.append(x)

print(newlist)

['apple', 'banana', 'mango']


In [25]:
my_list = [1, 2, 3, 4, 5]

# Initialize an index variable
index = 0

# Use a while loop to iterate through the list
while index < len(my_list):
    item = my_list[index]
    print(item)
    
    # Increment the index
    index += 1


1
2
3
4
5


## copy list items

In [48]:
# Create two lists with similar items
list1 = []
for i in range(50):
    list1.append(i)
print(list1)
list2 = list1[:]
print(list2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [49]:
# Combine the two lists into one
combined_list = list1 + list2

# Check the length of the combined list
total_length = len(combined_list)

# Print the combined list and its total length
print("Combined List:", combined_list)
print("Total Length:", total_length)


Combined List: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
Total Length: 100


## Dictionary

In [54]:
dictionary = {
    "key1": "value1",
    "key2": "value2",
    "key3": "value3",
    "key4": "value4",
    "key5": "value5",
}

for key, value in dictionary.items():
    print(key, value)


key1 value1
key2 value2
key3 value3
key4 value4
key5 value5


## Create two variables with similar names

In [53]:
# Create two variables with similar names
variable1 = "Savera Ansari"
variable2 = "Savera Ansari"

# Slice the first name from variable1 and the second name from variable2
first_name = variable1[:6]
second_name = variable2[7:]

# Print the output
print("First Name:", first_name)
print("Second Name:", second_name)


First Name: Savera
Second Name: Ansari


## DateTime

In [55]:
import datetime

class Person:
    def __init__(self, name, birth_date):
        self.name = name
        self.birth_date = birth_date

    def get_age(self):
        return (datetime.date.today() - self.birth_date).days

    def get_date_of_birth(self):
        return self.birth_date

    def get_date_100_days_ago(self):
        return self.birth_date - datetime.timedelta(days=100)


person = Person("John Doe", datetime.date(2003, 3, 8))

print(person.name)
print(person.get_age())
print(person.get_date_of_birth())
print(person.get_date_100_days_ago())



John Doe
7492
2003-03-08
2002-11-28


In [62]:
class Person:
    def __init__(self, name, address):
        self.name = name
        self.address = address

    def print_details(self):
        print(f"{self.name} lives in {self.address}")


person = Person("Ali", "Hayatabad")

person.print_details()


Ali lives in Hayatabad


## list maping and lambda

In [59]:
list1 = [1, 2, 3, 4, 5]
list2 = ["a", "b", "c", "d", "e"]

mapped_list = map(lambda x, y: x * y, list1, list2)

print(list(mapped_list))


['a', 'bb', 'ccc', 'dddd', 'eeeee']


In [60]:
# lambda to add 2 numbers
add = lambda x, y: x + y

# Usage
result = add(5, 3)
print(result)  # Output: 8


8


In [61]:
# Create two lists and map one on other. Use lambda function to add two variables.
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

mapped_list = map(lambda x, y: x + y, list1, list2)

print(list(mapped_list))


[7, 9, 11, 13, 15]


In [ ]:
# Create a list of words repeated words
word_list = ["apple", "banana", "cherry"]

# Repeat each word three times using a list comprehension
repeated_list = [word for word in word_list for _ in range(3)]

# Print the repeated list
print(repeated_list)


## stack

In [65]:
# Create a horizontal stack and repeat it 3 times for same values.
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])

horizontal_stack = np.hstack((array, array, array))

print(horizontal_stack)


[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]


In [ ]:
# create and eye for 4 rows in pythn
import numpy as np

# Create a 4x4 identity matrix
eye_matrix = np.eye(4)

# Print the identity matrix
print(eye_matrix)


In [ ]:
#diag function

import numpy as np

# Create a list of values
my_list = [1, 2, 3, 4]

# Use the diag function to create a diagonal matrix from the list
diagonal_matrix = np.diag(my_list)

# Print the diagonal matrix
print(diagonal_matrix)


In [66]:
# type array
array = np.array([1, 2, 3])

print(type(array))


<class 'numpy.ndarray'>


In [67]:
# Create an array of 0 to 20 numbers and find out its shape, then reshape it.

array = np.arange(21)

print(array.shape)

array = array.reshape(3, 7)

print(array)


(21,)
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [69]:
# Create an array with linespace of 2.4.
check
array = np.linspace(0, 10, 5)

print(array)


[ 0.   2.5  5.   7.5 10. ]


In [82]:
import numpy as np

# Create an array with a linspace of 2.4
start = 0
end = 10
step = 2.4
array = np.arange(start, end + step, step)

# Print the array
print(array)


[ 0.   2.4  4.8  7.2  9.6 12. ]


In [71]:
# Create an array for all one's.
array = np.ones(5)

print(array)

# Create an array for all zero's only.

array = np.zeros(5)

print(array)


[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]


In [72]:
# Create an array with random numbers.
array = np.random.rand(5)

print(array)


[0.69620944 0.60195231 0.90639634 0.5389179  0.21012943]


In [73]:
# Create an array with even numbers only.
array = np.arange(20)

even_numbers = array[array % 2 == 0]

print(even_numbers)


[ 0  2  4  6  8 10 12 14 16 18]


In [74]:
# Create an array with odd numbers only.
array = np.arange(20)

odd_numbers = array[array % 2 != 0]

print(odd_numbers)


[ 1  3  5  7  9 11 13 15 17 19]


In [75]:
# Create an array of Fibonacci numbers.
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)


array = []

for i in range(10):
    array.append(fibonacci(i))

print(array)


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [77]:
# Create an array of prime numbers.
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True


array = []

for i in range(2, 100):
    if is_prime(i):
        array.append(i)

print(array)


[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


In [78]:
# Write a program to print the Fibonacci sequence up to n terms.

def fibonacci(n):
    a, b = 0, 1
    for i in range(n):
        a, b = b, a + b
    return a


n = int(input("Enter the number of terms: "))
print("The Fibonacci sequence up to", n, "terms is:")
for i in range(n):
    print(fibonacci(i))


Enter the number of terms: 10
The Fibonacci sequence up to 10 terms is:
0
1
1
2
3
5
8
13
21
34


In [79]:
# Write a program to print the prime numbers up to n.
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True


n = int(input("Enter the number: "))
print("The prime numbers up to", n, "are:")
for i in range(2, n + 1):
    if is_prime(i):
        print(i)


Enter the number: 10
The prime numbers up to 10 are:
2
3
5
7


In [80]:
# Write a program to print the Palindrome numbers between 1 and n.
def is_palindrome(n):
    temp = n
    rev = 0
    while temp > 0:
        rev = rev * 10 + temp % 10
        temp //= 10
    return n == rev


n = int(input("Enter the number: "))
print("The Palindrome numbers between 1 and", n, "are:")
for i in range(1, n + 1):
    if is_palindrome(i):
        print(i)


Enter the number: 10
The Palindrome numbers between 1 and 10 are:
1
2
3
4
5
6
7
8
9


In [81]:
# Write a program to print the factorial of a number.
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)


n = int(input("Enter the number: "))
print("The factorial of", n, "is", factorial(n))


Enter the number: 20
The factorial of 20 is 2432902008176640000
