In [ ]:
import numpy as np

print(np.__version__)

1.22.4


In [ ]:
import array as array

In [ ]:
from numpy import*

In [ ]:
a = np.array([12,233,5,2,2,11,1])
a

array([ 12, 233,   5,   2,   2,  11,   1])

In [ ]:
a = np.array([1,23,54,4,5,3,2],float)
a

array([ 1., 23., 54.,  4.,  5.,  3.,  2.])

In [ ]:
print(type(a))
print(type(a.dtype))

<class 'numpy.ndarray'>
<class 'numpy.dtype[float64]'>


In [ ]:
a[:3]

array([ 1., 23., 54.])

In [ ]:
a[0]

1.0

In [ ]:
a[0] = 90
a

array([90., 23., 54.,  4.,  5.,  3.,  2.])

In [ ]:
b = np.array([[12,34,32,23],[12,32,5,6]])
b

array([[12, 34, 32, 23],
       [12, 32,  5,  6]])

In [ ]:
# b[2,1] #Error index out of bound

In [ ]:
b[1,2]

5

In [ ]:
b[1][2]

5

In [ ]:
a[1:]

array([23., 54.,  4.,  5.,  3.,  2.])

In [ ]:
c = np.array([[12,34,32,23],[12,32,5,6]])
c

array([[12, 34, 32, 23],
       [12, 32,  5,  6]])

In [ ]:
c[-1:,-2:]

array([[5, 6]])

In [ ]:
c.shape


(2, 4)

In [ ]:
c.dtype

dtype('int64')

In [ ]:
c

array([[12, 34, 32, 23],
       [12, 32,  5,  6]])

In [ ]:
len(c)

2

In [ ]:
12 in c

True

In [ ]:
-1 not in c

True

In [ ]:
1 in c

False

In [ ]:
c = np.array(range(12),float )
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
d = c.reshape(3,4)

In [ ]:
d

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
d.shape

(3, 4)

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b = a

In [ ]:
c= a.copy()  #b = a se b update hua magr c copy kia tha to wo original hai

In [ ]:
a[0] = 30
a

array([30,  2,  3])

In [ ]:
print(a)
print(b)
print(c)

[30  2  3]
[30  2  3]
[1 2 3]


The tolist() function returns a list that contains the same items of the original array.

In [ ]:
# Converted Array into List
n = np.array([[[1,2],[33,4],[45,54],[45,2]]])
print("This is simple array ")
print(n)
y = n.tolist()
print("After applying .tolist")
print(y)

This is simple array 
[[[ 1  2]
  [33  4]
  [45 54]
  [45  2]]]
After applying .tolist
[[[1, 2], [33, 4], [45, 54], [45, 2]]]


In [ ]:
a = np.array([1,2,3],float)
print(a)
b =a.tolist()
print(b)

[1. 2. 3.]
[1.0, 2.0, 3.0]


In [ ]:
a = np.array([1,2,3],float)
print(a)
s = a.tostring()
s

[1. 2. 3.]


<ipython-input-65-9343c13203b3>:3: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  s = a.tostring()


b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'

In [ ]:
# .fill method change all values
a.fill(0)
a

array([0., 0., 0.])

In [ ]:
a = np.array(range(90),float).reshape(10,9)
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23., 24., 25., 26.],
       [27., 28., 29., 30., 31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49., 50., 51., 52., 53.],
       [54., 55., 56., 57., 58., 59., 60., 61., 62.],
       [63., 64., 65., 66., 67., 68., 69., 70., 71.],
       [72., 73., 74., 75., 76., 77., 78., 79., 80.],
       [81., 82., 83., 84., 85., 86., 87., 88., 89.]])

In [ ]:
c = a.transpose()
print(c)

[[ 0.  9. 18. 27. 36. 45. 54. 63. 72. 81.]
 [ 1. 10. 19. 28. 37. 46. 55. 64. 73. 82.]
 [ 2. 11. 20. 29. 38. 47. 56. 65. 74. 83.]
 [ 3. 12. 21. 30. 39. 48. 57. 66. 75. 84.]
 [ 4. 13. 22. 31. 40. 49. 58. 67. 76. 85.]
 [ 5. 14. 23. 32. 41. 50. 59. 68. 77. 86.]
 [ 6. 15. 24. 33. 42. 51. 60. 69. 78. 87.]
 [ 7. 16. 25. 34. 43. 52. 61. 70. 79. 88.]
 [ 8. 17. 26. 35. 44. 53. 62. 71. 80. 89.]]


flatten() method in Python is used to return a copy of a given array in such a way that it is collapsed into one dimension.

In [ ]:
a.flatten()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89.])

In [ ]:
a

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23., 24., 25., 26.],
       [27., 28., 29., 30., 31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49., 50., 51., 52., 53.],
       [54., 55., 56., 57., 58., 59., 60., 61., 62.],
       [63., 64., 65., 66., 67., 68., 69., 70., 71.],
       [72., 73., 74., 75., 76., 77., 78., 79., 80.],
       [81., 82., 83., 84., 85., 86., 87., 88., 89.]])

In [ ]:
d

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
e = d.copy()
e

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
c

array([[ 0.,  9., 18., 27., 36., 45., 54., 63., 72., 81.],
       [ 1., 10., 19., 28., 37., 46., 55., 64., 73., 82.],
       [ 2., 11., 20., 29., 38., 47., 56., 65., 74., 83.],
       [ 3., 12., 21., 30., 39., 48., 57., 66., 75., 84.],
       [ 4., 13., 22., 31., 40., 49., 58., 67., 76., 85.],
       [ 5., 14., 23., 32., 41., 50., 59., 68., 77., 86.],
       [ 6., 15., 24., 33., 42., 51., 60., 69., 78., 87.],
       [ 7., 16., 25., 34., 43., 52., 61., 70., 79., 88.],
       [ 8., 17., 26., 35., 44., 53., 62., 71., 80., 89.]])

In [ ]:
b

[1.0, 2.0, 3.0]

In [ ]:
np.concatenate((d,e))  # only run with same rows and columns



array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a = np.array([[2,3,2],[5,6,8]],float)
b = np.array([[22,32,42],[57,96,98]],float)
np.concatenate((a,b))

array([[ 2.,  3.,  2.],
       [ 5.,  6.,  8.],
       [22., 32., 42.],
       [57., 96., 98.]])

In [ ]:
a = np.array([[2,3,2],[5,6,8]],float)
b = np.array([[22,32,42],[57,96,98]],float)
np.concatenate((a,b), axis = 0)  #when axis = 0 it runs Vertically

array([[ 2.,  3.,  2.],
       [ 5.,  6.,  8.],
       [22., 32., 42.],
       [57., 96., 98.]])

In [ ]:
np.concatenate((a,b), axis = 1)  #when axis = 1 it runs Horizontally

array([[ 2.,  3.,  2., 22., 32., 42.],
       [ 5.,  6.,  8., 57., 96., 98.]])