# **Arrays**

append()	Adds an element at the end of the list

clear()	Removes all the elements from the list

copy()	Returns a copy of the list

count()	Returns the number of elements with the specified value

extend()	Add the elements of a list (or any iterable), to the end of the current list

index()	Returns the index of the first element with the specified value

insert()	Adds an element at the specified position

pop()	Removes the element at the specified position

remove()	Removes the first item with the specified value

reverse()	Reverses the order of the list

sort()	Sorts the list

In [144]:
cars = ["Ford", "Volvo", "BMW","ferrari"]

In [145]:
cars[0] = "Toyota"

In [146]:
x = len(cars)

In [147]:
for x in cars:
  print(x)

Toyota
Volvo
BMW
ferrari


In [149]:
cars.append("Honda")

In [150]:
cars.pop(1)

'Volvo'

In [152]:
# cars.remove("Volvo")

# **Arrays using numpy**


In [17]:
import numpy as np

In [18]:
a = np.array([12,3,4,5,2,4,41,1],float)
a

array([12.,  3.,  4.,  5.,  2.,  4., 41.,  1.])

In [19]:
type(a)

numpy.ndarray

In [20]:
a[:2]

array([12.,  3.])

In [21]:
a[3]

5.0

In [23]:
a[0:6:2]

array([5., 4., 2.])

In [22]:
a[0] = 5
a

array([ 5.,  3.,  4.,  5.,  2.,  4., 41.,  1.])

# **Two D Array**

In [25]:
b = np.array([[12,12,455,5],[23,6,7,4]])
b

array([[ 12,  12, 455,   5],
       [ 23,   6,   7,   4]])

In [156]:
a = np.array([[1,3,5,6],[56,4,3,9]],float)
a

array([[ 1.,  3.,  5.,  6.],
       [56.,  4.,  3.,  9.]])

In [157]:
a[0,0]

1.0

In [158]:
print(a[1][2])

3.0


In [31]:
a[0,1]

3.0

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
a[1,:]

array([4., 5., 6.])

In [34]:
a[:,1]

array([2., 5.])

In [35]:
a[-1:-2]

array([], shape=(0, 3), dtype=float64)

In [36]:
a[-1:,-2:]

array([[5., 6.]])

In [43]:
a.shape

(2, 3)

In [45]:
b.shape

(2, 4)

In [ ]:
a.dtype

dtype('float64')

In [47]:
len(b)

2

In [48]:
2 in b

False

In [49]:
0 in a

False

In [51]:
a = np.array(range(10),float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
a = a.reshape((5,2))
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [55]:
a.shape

(5, 2)

In [57]:
b = a
c = a.copy()
c



array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [62]:
a[4,1]

9.0

In [65]:
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [66]:
b

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [67]:
c

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

**tolist()**

**tostring()**

**fromstring()**

**a.reshape()**

**transpose()**

**flatten()**

In [68]:
a.tolist()

[[0.0, 1.0], [2.0, 3.0], [4.0, 5.0], [6.0, 7.0], [8.0, 9.0]]

In [69]:
list(a)

[array([0., 1.]),
 array([2., 3.]),
 array([4., 5.]),
 array([6., 7.]),
 array([8., 9.])]

In [71]:
s = a.tostring()
s

<ipython-input-71-bdbfd1da95fa>:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  s = a.tostring()


b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@\x00\x00\x00\x00\x00\x00\x1c@\x00\x00\x00\x00\x00\x00 @\x00\x00\x00\x00\x00\x00"@'

In [72]:
np.fromstring(s)

<ipython-input-72-6c2008ed54c7>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring(s)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [74]:
a.fill(01)
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [76]:
a = np.array(range(8),float).reshape((2,4))
a

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]])

In [77]:
a.transpose()

array([[0., 4.],
       [1., 5.],
       [2., 6.],
       [3., 7.]])

In [82]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a.flatten()


array([1., 2., 3., 4., 5., 6.])

# **Concatenation**
**newaxis**

In [84]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [88]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)

In [91]:
np.concatenate((a,b), axis=0)  #vertically downward row

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [92]:
np.concatenate((a,b), axis=1)    #horizontally across columns

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [93]:
a[:,np.newaxis]

array([[[1., 2.]],

       [[3., 4.]]])

In [95]:
a[:,np.newaxis].shape

(2, 1, 2)

# **Other Way to create Array**

In [96]:
np.arange(5, dtype=float)


array([0., 1., 2., 3., 4.])

In [97]:
np.arange(1, 6, 2, dtype=int)


array([1, 3, 5])

In [98]:
np.ones((2,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [99]:
np.zeros((2,3), dtype=float)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [100]:
np.identity(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [101]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
a + b
a-b
a * b
b / a
a % b
b**a


array([  5.,   4., 216.])

In [102]:
a + b

array([6., 4., 9.])

In [103]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [104]:
a = np.array([1.1, 1.5, 1.9], float)
np.floor(a)

array([1., 1., 1.])

In [105]:
np.ceil(a)

array([2., 2., 2.])

In [106]:
np.rint(a)

array([1., 2., 2.])

In [107]:
np.pi

3.141592653589793

# **Array ITeration**


In [108]:
a = np.array([1, 4, 5], int)
for x in a:
  print(x)

1
4
5


In [109]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
  print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [110]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for (x, y) in a:
  print(x * y)

2.0
12.0
30.0


In [114]:
np.sum(a)

21.0

In [113]:
np.prod(a)

720.0

In [119]:
a.min()
a.max()
a.mean()
a.std()
a.var()

2.9166666666666665

In [121]:
a.sort()
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [122]:
np.unique(a)

array([1., 2., 3., 4., 5., 6.])

In [123]:
a.diagonal()

array([1., 4.])

# **Conditions**

In [131]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
a > b


array([ True, False, False])

In [132]:
 a == b


array([False,  True, False])

In [133]:
any(a > 2)

True

In [134]:
all(a>2)

False

**Selection**

In [135]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([2., 2., 4., 8., 6., 4.])

In [136]:
a = np.array([2, 4, 6, 8], float)
a[[0, 0, 1, 3, 2, 1]]

array([2., 2., 4., 8., 6., 4.])

In [137]:
 a = np.array([[1, 4], [9, 16]], float)
 b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

**Random**

In [138]:
np.random.rand(5)

array([0.17313421, 0.08262794, 0.24576023, 0.11205256, 0.73784871])

In [139]:
np.random.rand(2,3)

array([[0.20829113, 0.38218491, 0.28514417],
       [0.89045965, 0.26280636, 0.71703308]])

In [140]:
np.random.rand(6).reshape((2,3))

array([[0.04348295, 0.24489109, 0.83077307],
       [0.01358807, 0.30720483, 0.9115124 ]])

In [141]:
np.random.randint(5, 10)

7

In [162]:
from array import *

T = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]
for r in T:
   for c in r:
      print(c,end = " ")
   print()

11 12 5 2 
15 6 10 
10 8 12 5 
12 15 8 6 


**insert value**

In [164]:
T = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]

T.insert(2, [0,5,11,13,6])
T

[[11, 12, 5, 2],
 [15, 6, 10],
 [0, 5, 11, 13, 6],
 [10, 8, 12, 5],
 [12, 15, 8, 6]]

In [165]:
T = [[11, 12, 5, 2], [15, 6,10], [10, 8, 12, 5], [12,15,8,6]]

T[2] = [11,9]
T[0][3] = 7
T

[[11, 12, 5, 7], [15, 6, 10], [11, 9], [12, 15, 8, 6]]